fix: update pre-submit to ubuntu24 (#4080)
# Summary

Update pre-submit to use ubuntu24

https://github.com/slsa-framework/slsa-github-generator/actions/runs/12999310515/job/36254511524?pr=4041

```
Run ./.github/workflows/scripts/pre-submit.e2e.go.default.sh
✖ ubuntu24 == ubuntu22 :: .predicate.invocation.environment.os should be ubuntu22
Error: Process completed with exit code 1.
```

## Testing Process

This PR's pre-submits should pass.

## Checklist

- [x] Review the contributing
[guidelines](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
- [x] Add a reference to related issues in the PR description.
- [ ] Update documentation if applicable.
- [x] Add unit tests if applicable.
- [ ] Add changes to the
[CHANGELOG](https://github.com/slsa-framework/slsa-github-generator/blob/main/CHANGELOG.md)
if applicable.

Signed-off-by: Ramon Petgrave <32398091+ramonpetgrave64@users.noreply.github.com>