fix: maven e2e: remove verify job (#3748)
# Summary

Followup to #3746

Removes the verify job, which won't work, because the ref will be
incorrect.

-
https://github.com/slsa-framework/slsa-github-generator/actions/runs/10115454784/job/27976327657#step:5:1

```
WARNING: Insecure SLSA_VERIFIER_TESTING is enabled.
Verifying artifact ./target/test-java-project-1.21.97.jar: FAILED: invalid ref: "refs/heads/main": unexpected ref type: "heads"

FAILED: SLSA verification failed: invalid ref: "refs/heads/main": unexpected ref type: "heads"
Error: Process completed with exit code 1.
```

## Testing Process

The e2e test is executed in this PR, which now passes.

## Checklist

- [x] Review the contributing
[guidelines](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
- [x] Add a reference to related issues in the PR description.
- [ ] Update documentation if applicable.
- [x] Add unit tests if applicable.
- [ ] Add changes to the
[CHANGELOG](https://github.com/slsa-framework/slsa-github-generator/blob/main/CHANGELOG.md)
if applicable.

---------

Signed-off-by: Ramon Petgrave <32398091+ramonpetgrave64@users.noreply.github.com>
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>
Signed-off-by: Ramon Petgrave <32398091+ramonpetgrave64@users.noreply.github.com>